# Generated by Django 4.2.30 on 2026-09-22 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('requested_site_visit', models.BooleanField(default=False)),
                ('inquired_sqft', models.IntegerField(default=2200)),
                ('inquired_budget_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('city_region', models.CharField(default='Mumbai MMR', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('user_query', models.TextField()),
                ('bot_response', models.TextField()),
                ('inquired_sqft', models.IntegerField(default=1500)),
                ('estimated_cost_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='Mumbai MMR', max_length=100)),
                ('base_rate_per_sqft', models.DecimalField(decimal_places=2, default=1850.0, max_digits=10)),
                ('cement_ratio', models.DecimalField(decimal_places=2, default=0.4, max_digits=6)),
                ('steel_ratio', models.DecimalField(decimal_places=4, default=0.0035, max_digits=6)),
                ('brick_ratio', models.DecimalField(decimal_places=2, default=18.0, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('bhk_type', models.CharField(default='3 BHK', max_length=20)),
                ('sqft', models.IntegerField(default=2000)),
                ('floors', models.IntegerField(default=2)),
                ('blueprint_2d', models.URLField(blank=True, max_length=500, null=True)),
                ('render_3d', models.URLField(blank=True, max_length=500, null=True)),
                ('room_hotspots', models.JSONField(default=list, help_text='Hotspot room specs JSON')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='Structural', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=30)),
                ('trend', models.CharField(default='0.0%', max_length=20)),
                ('brand', models.CharField(default='Generic', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='Turnkey Construction', max_length=100)),
                ('location', models.CharField(default='Mumbai, India', max_length=150)),
                ('sqft', models.IntegerField(default=2400)),
                ('duration_months', models.IntegerField(default=8)),
                ('completed_year', models.IntegerField(default=2026)),
                ('estimated_cost_inr', models.DecimalField(decimal_places=2, default=7500000.0, max_digits=14)),
                ('before_image', models.URLField(max_length=500)),
                ('after_image', models.URLField(max_length=500)),
                ('gallery_images', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('TURNKEY', 'Turnkey Home Construction'), ('PLANNING', 'Architectural Planning & 3D Design'), ('STRUCTURAL', 'Structural Engineering & Detailing'), ('INTERIOR', 'Interior Architecture & Finishing'), ('RENOVATION', 'Full Home Renovation & Remodeling')], default='TURNKEY', max_length=30)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('starting_price_inr', models.DecimalField(decimal_places=2, default=1750.0, max_digits=12)),
                ('unit', models.CharField(default='per sq ft', max_length=50)),
                ('features', models.JSONField(default=list, help_text='List of bullet features')),
                ('icon', models.CharField(default='Building2', max_length=50)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=150)),
                ('bhk_type', models.CharField(default='3 BHK', max_length=50)),
                ('sqft', models.IntegerField(default=450)),
                ('dimensions', models.CharField(default='20.0 ft x 22.5 ft', max_length=100)),
                ('finishes', models.TextField(default='Italian Marble Flooring, UPVC Double Glazed Windows, Cove Lighting')),
                ('blueprint_2d', models.URLField(blank=True, max_length=500, null=True)),
                ('render_3d', models.URLField(blank=True, max_length=500, null=True)),
                ('x_percent', models.IntegerField(default=50)),
                ('y_percent', models.IntegerField(default=50)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_layouts', to='estimator.project')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('message', models.TextField()),
                ('calculation_snapshot', models.JSONField(blank=True, default=dict, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='estimator.chatbotsession')),
            ],
        ),
    ]
