# Generated by Django 4.2.30 on 2026-09-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_mason_daily_wage', models.DecimalField(decimal_places=2, default=950.0, max_digits=10)),
                ('skilled_labour_daily_wage', models.DecimalField(decimal_places=2, default=800.0, max_digits=10)),
                ('helper_daily_wage', models.DecimalField(decimal_places=2, default=650.0, max_digits=10)),
                ('other_worker_daily_wage', models.DecimalField(decimal_places=2, default=600.0, max_digits=10)),
                ('rcc_structure_rate_sqft', models.DecimalField(decimal_places=2, default=240.0, max_digits=10)),
                ('brickwork_plaster_rate_sqft', models.DecimalField(decimal_places=2, default=110.0, max_digits=10)),
                ('tile_flooring_rate_sqft', models.DecimalField(decimal_places=2, default=45.0, max_digits=10)),
                ('plumbing_elec_rate_sqft', models.DecimalField(decimal_places=2, default=160.0, max_digits=10)),
                ('painting_rate_sqft', models.DecimalField(decimal_places=2, default=22.0, max_digits=10)),
                ('daily_mason_team_output_sqft', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('working_hours', models.IntegerField(default=8)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('base_material_rate_per_sqft', models.DecimalField(decimal_places=2, default=1200.0, max_digits=10)),
                ('flooring_spec', models.CharField(default='Ceramic Tiles (600x600mm)', max_length=255)),
                ('plumbing_spec', models.CharField(default='Standard Sanitary & CP Fittings', max_length=255)),
                ('electrical_spec', models.CharField(default='Modular Switches & Copper Wiring', max_length=255)),
                ('paint_spec', models.CharField(default='Tractor Emulsion Paint', max_length=255)),
                ('doors_windows_spec', models.CharField(default='Flush Doors & Aluminium Windows', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='estimated_labour_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='estimated_material_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='labour_rates_used',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='material_prices_used',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='selected_cement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='selected_package',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='selected_steel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='selected_workers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='state',
            field=models.CharField(choices=[('START', 'Start'), ('COLLECT_SQFT', 'Collect Square Feet'), ('COLLECT_LOCATION', 'Collect Location'), ('RESEARCH', 'Web Researching'), ('SELECT_CEMENT', 'Select Cement'), ('SELECT_STEEL', 'Select Steel'), ('SELECT_WORKFORCE', 'Select Workforce'), ('CALCULATE_PACKAGES', 'Calculate Packages'), ('SELECT_PACKAGE', 'Select Package'), ('CONFIRM', 'Confirm Estimate'), ('COMPLETED', 'Completed')], default='START', max_length=30),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='total_estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='web_sources_used',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='grade',
            field=models.CharField(blank=True, default='Standard', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='source',
            field=models.CharField(default='Admin Database', max_length=150),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatbotsession',
            name='city_region',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='chatbotsession',
            name='inquired_sqft',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
