# Generated by Django 4.2.30 on 2026-09-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0002_labourrate_packageconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsession',
            name='pending_material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
